Expand anndata compatibility
owkin/PyDESeq2 pull request #115
Opened 2023-04-20 15:08 UTC by scottgigante-immunai

#### Reference Issue or PRs
Fixes #114 

#### What does your PR implement? Be specific.
Expands anndata compatibility

2023-04-21 07:48 UTC, BorisMuzellec commented
Hi @scottgigante-immunai, thanks for opening this PR!

I agree that it would be best to use the latest version of `anndata`.

Unfortunately I probably won't have much time to work on this in the next few days/weeks, but if you feel like investigating why tests fail, I'd be happy to review this PR once it passes tests. In the meantime, I can also help to some extent.

2023-04-21 13:12 UTC, scottgigante-immunai commented
Thanks @BorisMuzellec ! Looks like I need your approval to run the tests, but otherwise I'm happy to debug.

2023-04-24 13:48 UTC, scottgigante-immunai commented
@BorisMuzellec this should be good to go :)

2023-04-26 07:47 UTC, BorisMuzellec requested changes

2023-04-26 13:27 UTC, scottgigante-immunai commented on pydeseq2/dds.py
> -
I didn't remove this, I just moved it down -- as written, the current code doesn't guard against _both_ being set, only against _neither_ being set. I'm happy to put that in! I just moved the _neither_ part down to keep mypy happy.

2023-04-26 14:24 UTC, BorisMuzellec commented on pydeseq2/dds.py
> -
Indeed, for some reason I assumed there was a test to guard agains both being set :sweat_smile:. 

Thanks a lot for implementing this!

2023-04-26 15:26 UTC, merged